Homework 1
KonTroAl/HW_PyQT pull request #1
Opened 2021-07-08 10:58 UTC by KonTroAl

2021-07-08 22:14 UTC, Ma007ks requested changes

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_1.py
> +        # ipv4 = ipaddress.ip_address(i)
Закомментированный код нужно удалить

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_1.py
> +# До конца так и не понял последнее условие с созданием ip-адреса сетевого узла через функцию ip_address().
ip-адреса в hosts стоит обернуть в `ip_address`

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_2.py
> +def host_range_ping(hos, number):
```suggestion
def host_range_ping(host, number):
```

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_2.py
> +hosts = '80.0.1.1'
Переменную лучшее перенести вниз и использовать `ipaddress.ip_network` (она задаст необходимые адреса, по которым нужно проитерировать)

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_2.py
> +    a = []
Имя стоит поменять на более подходящее

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_2.py
> +# val = input('Введите начальный ip-адрес: ')
Закомментированный код нужно удалить

2021-07-08 22:14 UTC, Ma007ks commented on homework_1/task_3.py
> +# task 3
Нужно поправить то же, что и в task_2 🙂

2021-07-10 11:06 UTC, KonTroAl commented
Поправил все дз

2021-07-10 11:08 UTC, KonTroAl commented on homework_1/task_3.py
> +# task 3
Постарался учесть все замечания и поправил код, скрипт по 4 заданию лежит в my_chat\chat\start_chat.py

2021-07-10 12:12 UTC, Ma007ks requested changes
Совет: в модулях, которые одновременно имеют полезные функции и имеют для примера запуск этих функций, пример выносить в условие `if __name__ == '__main__'`. Это позволит их импортировать без лишних запусков.

2021-07-10 12:12 UTC, ionsome commented on my_chat/chat/start_chat.py
> +    while n > 0:
Если n > 0, то условие превращается в `while True` 🙂

2021-07-10 12:12 UTC, Ma007ks commented on homework_1/task_2.py
> +    for i in range(num):
Передавать num по заданию не обязательно, проитерировать можно `subnet` напрямую

2021-07-27 11:30 UTC, merged