Homework 2
KonTroAl/HW_PyQT pull request #2
Opened 2021-07-12 10:44 UTC by KonTroAl

Не до конца понимаю, как реализовать проверку основного класса через мета класс, первая пока относительно рабочая идея это решение через assert, но скорее всего есть вариант проще

2021-07-20 17:41 UTC, Ma007ks requested changes
Заочно ставлю хорошо, но задание нужно доделать.
Я добавил незаконченные примеры решений для дескриптора и метаклассов, их нужно взять за основу.

2021-07-20 17:41 UTC, ionsome commented on my_chat/chat/my_client.py
> +class ClientVerifier(metaclass=ClientVerifierMeta):
Зачем нужен этот класс?

2021-07-20 17:41 UTC, Ma007ks commented on my_chat/chat/my_client.py
> +            if key == 'start_connection':
У класса может и не быть атрибута с именем `start_connection`

2021-07-20 17:41 UTC, Ma007ks commented on my_chat/chat/my_server.py
> +class PortVerifier:
нет метода `__get__`

2021-07-20 17:41 UTC, Ma007ks commented on my_chat/chat/my_server.py
> +class ServerVerifier(metaclass=ServerVerifierMeta):
Зачем нужен этот класс?

2021-07-22 11:39 UTC, KonTroAl commented on my_chat/chat/my_server.py
> +class ServerVerifier(metaclass=ServerVerifierMeta):
делал по методичке, потом уже понял, что этот класс не обязателен, а во всем остальном постарался исправить все замечания и доделал ДЗ по образцу, который вы скинули

2021-07-27 11:35 UTC, merged